Change login to DevTunnels to use bash and OIDC token
Updated the login step to use bash instead of pwsh and changed the method for retrieving the OIDC token.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -70,17 +70,32 @@ runs:
           echo "pathname=${{ steps.install-other.outputs.pathname }}" >> $env:GITHUB_OUTPUT
         }
 
+#    - name: Login to DevTunnels
+#      shell: pwsh
+#      run: |
+#        $response = Invoke-RestMethod -Uri "$env:ACTIONS_ID_TOKEN_REQUEST_URL" -Headers @{ "Authorization" = "Bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN" }
+#        $id_token = $response.value
+#        & $env:DEVTUNNEL user login --entra --sp-tenant-id $env:TENANT_ID --sp-client-id $env:CLIENT_ID --federated-token "$id_token"
+#      env:
+#        DEVTUNNEL: ${{ steps.install.outputs.pathname }}
+#        TENANT_ID: ${{ inputs.tenant-id }}
+#        CLIENT_ID: ${{ inputs.client-id }}
+
     - name: Login to DevTunnels
-      shell: pwsh
+      shell: bash
       run: |
-        $response = Invoke-RestMethod -Uri "$env:ACTIONS_ID_TOKEN_REQUEST_URL" -Headers @{ "Authorization" = "Bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN" }
-        $id_token = $response.value
-        & $env:DEVTUNNEL user login --entra --sp-tenant-id $env:TENANT_ID --sp-client-id $env:CLIENT_ID --federated-token "$id_token"
+        OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r .value)
+        if [ -z "$OIDC_TOKEN" ] || [ "$OIDC_TOKEN" == "null" ]; then
+          echo "::error::Failed to retrieve OIDC token."
+          exit 1
+        fi
+
+        $DEVTUNNEL user login --entra --sp-tenant-id $TENANT_ID --sp-client-id $CLIENT_ID --federated-token "$OIDC_TOKEN"
       env:
         DEVTUNNEL: ${{ steps.install.outputs.pathname }}
         TENANT_ID: ${{ inputs.tenant-id }}
         CLIENT_ID: ${{ inputs.client-id }}
-
+  
     - name: Start DevTunnel
       shell: bash
       run: |
